name: academyfun
description: "Application Conseling"
publish_to: "none"
version: 0.1.3

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.6.2
  intl: ^0.20.1
  loading_animation_widget: ^1.3.0
  open_file: ^3.5.10
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  salomon_bottom_bar: ^3.3.2
  supabase_flutter: ^2.8.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
